apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Name}}
data:
  # all-queries is used by DNS tests.
  all-queries: |
    kubernetes.cluster.local A
    kubernetes.svc.cluster.local A
    kubernetes.default.svc.cluster.local A
    google.com.svc.cluster.local A
    google.com.svc.cluster.local AAAA
    google.com.default.svc.cluster.local A
    google.com.default.svc.cluster.local AAAA
    google.com.cluster.local A
    google.com.cluster.local AAAA
    google.com A
    google.com AAAA
    small-service-0 A
    small-service-0.{{ .Namespace }} A
    small-service-0.{{ .Namespace }}.svc.cluster.local A
    medium-service-0 A
    medium-service-0.{{ .Namespace }} A
    medium-service-0.{{ .Namespace }}.svc.cluster.local A
    big-service-0 A
    big-service-0.{{ .Namespace }} A
    big-service-0.{{ .Namespace }}.svc.cluster.local A
